### ISSUE TITLE
not firing past 10km

### ISSUE THREAD

**Issue by Azutte** [iChun/PortalGunClassic#3]

**Comment by Azutte** [comment]
![2018-11-26_22 34 08](https://user-images.githubusercontent.com/6581284/49063223-8cf01700-f1cb-11e8-847b-c653ddcfbde9.png)
![2018-11-26_23 28 01](https://user-images.githubusercontent.com/6581284/49065517-17884480-f1d3-11e8-8950-c074cd75e035.png)

This Issue has been a couple different things in the last two hours (as I've kept investigating and editing it) but I'm leaving it up because I'm pretty sure they shouldn't be doing this.

Additionally: It took me a long time to understand that the config that says `Maximum Portal Firing Distance` and `Maximum distance to fire portals from the Portal Gun` actually refers not to the player, but actually a range out from `0,0`. Is that... intentional, having it be a set area of the map you can fire portals within? A 20k-wide cylinder centered on spawn? Would you be so kind as to change the text on the config in favor of added clarity?

**Comment by iChun** [comment]
This issue was fixed for PG 7.1.0
