### ISSUE TITLE
Invisible Portal Gun and Gravity Gun Sprite/Model

### ISSUE THREAD

**Issue by Phoenixstar1172** [iChun/PortalGunClassic#5]
I've tried installing the Portal Gun mod into a fresh Forge install on the latest dev version of Forge, and when trying to use the Portal Gun the sprite is invisible, yet the gun works exactly as intended and the effects for the portals are flawless. But the sprite/model of the gun itself seems to be missing or broken. I can't find any other items either through searching, so I imagine either the current build only includes the Portal Guns or the other items are also invisible.

The Gravity Gun mod is having the same issue.

Using
iChunUtil-1.12.2-7.1.4
Portalgun-1.12.2-7.0.2
GravityGun-1.12.2-7.0.1

Forge Version: 1.12.2 - 14.23.5.2808

All downloaded from the latest files on the curse forge website. I don't know if "PortalGunClassic" is the same thing as these newest curse forge mod versions, but I couldn't find anywhere else to post a bug report besides basic comment sections that appeared to have been ignored.

**Comment by Phoenixstar1172** [comment]
So... I added over 100 mods after this in a private modpack, and decided to keep the Portalgun mod in for the fun of it. It's still useful even if I cant see the gun in my hands... but now it is working, the model showing perfectly. I don't know what mod fixed it, or if it had anything to do with a mod in the first place. Ill see if I can figure this out tomorrow, and try removing some of the mods that might such as Optifine or CTM.

**Comment by Phoenixstar1172** [comment]
It's optifine... go figure. I should've realized that a complicated model like the Portal Gun would require a mod which allows such to work in Minecraft.

**Comment by iChun** [comment]
Hold up, with portal gun are we talking about? This repo is for Portal Gun
Classic. The issue tracker for Portal Gun is a different repository

**Comment by Phoenixstar1172** [comment]
I couldn’t find that repository, only this one from a google search. But yeah, this is for the 1.12.2 Portal Gun and Gravity Gun mods

**Comment by iChun** [comment]
Fixed for iChunUtil 7.2.1
