### ISSUE TITLE
For 1.7.10 versions

### ISSUE THREAD

**Issue by WatoLua** [iChun/PortalGunClassic#7]
Hi,

First, thanks for the mod, portal is incredible.

I would like to have portal gun mod in 1.7.10. The current version of your mod in 1.7.10 is not finished and has some crashs.
So can you update this portal gun classic mod version in 1.7.10 or post in open source your 1.7.10 version for the community resolve problems if you don't want to support this version please.

Thank you for your answer

Oxas

**Comment by iChun** [comment]
This project was a remake of the first version of Portal Gun. This repo was to expose the code for it and left for educational purposes. I will not be updating this project any further than its current state, sorry.
